/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Commands/About.vue')['default']
    AutoSuggestions: typeof import('./src/components/AutoSuggestions.vue')['default']
    CommandHistory: typeof import('./src/components/Commands/CommandHistory.vue')['default']
    Echo: typeof import('./src/components/Commands/Echo.vue')['default']
    Help: typeof import('./src/components/Commands/Help.vue')['default']
    HelpMessage: typeof import('./src/components/HelpMessage.vue')['default']
    LinePrefix: typeof import('./src/components/LinePrefix.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    OutputHistory: typeof import('./src/components/OutputHistory.vue')['default']
    Projects: typeof import('./src/components/Commands/Projects.vue')['default']
    Quote: typeof import('./src/components/Commands/Quote.vue')['default']
    Secret: typeof import('./src/components/Commands/Secret.vue')['default']
    TerminalInput: typeof import('./src/components/TerminalInput.vue')['default']
    Weather: typeof import('./src/components/Commands/Weather.vue')['default']
    Welcome: typeof import('./src/components/Commands/Welcome.vue')['default']
    WhoAmI: typeof import('./src/components/Commands/WhoAmI.vue')['default']
  }
}
